[RFC] v4l: subdev: subdev_fh->pad depends on CONFIG_VIDEO_V4L2_SUBDEV_API
If CONFIG_VIDEO_V4L2_SUBDEV_API=n:

    drivers/media/v4l2-core/v4l2-subdev.c: In function 'subdev_open':
    drivers/media/v4l2-core/v4l2-subdev.c:86:106: error: 'struct v4l2_subdev_fh' has no member named 'pad'

v4l2_subdev_fh.pad exists only if CONFIG_VIDEO_V4L2_SUBDEV_API is
enabled.

Protect the call to v4l2_subdev_call() by an #ifdef to fix this.

Fixes: e1879dda1574a349 ("v4l: subdev: Call pad init_cfg operation when opening subdevs")
Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>